apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  selector:
    app: my-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
